FROM noaa-medallion-pipeline-airflow-common:latest

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    default-jdk-headless \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

USER airflow

RUN pip install --quiet pytest pytest-mock
