name: noaa-medallion-pipeline

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow

  airflow-common: &airflow-common
    build: .
    user: root 
    env_file:
      - .env
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=fb39118918e32145a1d07a71c8ffb00c=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__LOAD_DEFAULT_CONNECTIONS=False
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - PYTHONPATH=/opt/airflow
      - AIRFLOW_VAR_PROJECT_ID=${AIRFLOW_VAR_PROJECT_ID}
      - AIRFLOW_VAR_REGION=${AIRFLOW_VAR_REGION}
      - AIRFLOW_VAR_DATA_LAKE_ROOT_PATH=${AIRFLOW_VAR_DATA_LAKE_ROOT_PATH}
    volumes:
      # local
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./common:/opt/airflow/common
      - ./logs:/opt/airflow/logs
      - ./keys:/opt/airflow/keys
      - ./seeds:/opt/airflow/seeds
      # SHARED NAMED VOLUMES: 
      - landed-vol:/opt/airflow/landed
      - bronze-vol:/opt/airflow/bronze
      - silver-vol:/opt/airflow/silver
      - gold-vol:/opt/airflow/gold
    depends_on:
      postgres:
        condition: service_healthy

  airflow-init:
    <<: *airflow-common
    command: >
      bash -c "airflow db init &&
      airflow users create --username admin --password admin --firstname First --lastname Last --role Admin --email admin@example.com"

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    env_file: 
      - .env
    ports:
      - "8080:8080"
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always

  # spark:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.spark
  #   user: root 
  #   command: >
  #     /opt/spark/bin/spark-submit 
  #     --class org.apache.spark.sql.connect.service.SparkConnectServer 
  #     --packages org.apache.spark:spark-connect_2.12:3.4.0 
  #     spark-internal
  #   ports:
  #     - "15002:15002"  
  #     - "4040:4040"   
  #   volumes:
  #     - landed-vol:/opt/airflow/landed
  #     - bronze-vol:/opt/airflow/bronze
  #     - silver-vol:/opt/airflow/silver
  #     - gold-vol:/opt/airflow/gold

  spark:
    image: deltaio/delta-docker:4.0.1
    user: root
    # Force the image to ignore the "Choose an Interface" interactive menu
    entrypoint: ["/opt/spark/bin/spark-submit"]
    command: >
      --packages io.delta:delta-spark_2.13:4.0.0
      --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension 
      --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog 
      --conf spark.sql.catalog.spark_catalog.warehouse=/opt/spark/spark-warehouse
      --conf spark.driver.bindAddress=0.0.0.0
      --class org.apache.spark.sql.connect.service.SparkConnectServer 
      spark-internal
    ports:
      - "15002:15002"
      - "4040:4040"
    volumes:
      - landed-vol:/opt/airflow/landed
      - bronze-vol:/opt/airflow/bronze
      - silver-vol:/opt/airflow/silver
      - gold-vol:/opt/airflow/gold
volumes:
  landed-vol:
  bronze-vol:
  silver-vol:
  gold-vol: