FROM apache/spark-py:v3.4.0

# 1. Switch to root temporarily to perform admin tasks
USER root

# 2. Create the package cache directory and the logs directory
# 3. Change ownership (chown) to the restricted spark user (UID 185)
RUN mkdir -p /opt/spark/.ivy2 && \
    chown -R 185:0 /opt/spark/.ivy2

# 4. Drop privileges and switch BACK to the secure, non-root user
USER 185