import subprocess

subprocess.check_call(["python", "scripts/ingestion/ingest_met_office_metadata_to_landed.py"])
print("ingest_met_office_metadata_to_landed.py complete")
subprocess.check_call(["python", "scripts/bronze/load_met_office_metadata_to_bronze.py"])
print("load_met_office_metadata_to_bronze.py complete")
subprocess.check_call(["python", "scripts/silver/load_met_office_metadata_to_silver.py"])
print("load_met_office_metadata_to_silver.py complete")
subprocess.check_call(["python", "scripts/ingestion/ingest_met_office_land_observations_to_landed.py"])
print("ingest_met_office_land_observations_to_landed.py complete")
subprocess.check_call(["python", "scripts/bronze/load_met_office_land_observations_to_bronze.py"])
print("load_met_office_land_observations_to_bronze.py complete")
subprocess.check_call(["python", "scripts/silver/load_met_office_land_observations_to_silver.py"])
print("load_met_office_land_observations_to_silver.py complete")
subprocess.check_call(["python", "scripts/gold/load_fact_weather_metrics.py"])
print("load_fact_weather_metrics.py complete")
print("done")
